# Generated by Django 5.2 on 2025-04-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OriginalQuery', models.TextField()),
                ('tone', models.CharField(max_length=1000)),
                ('intent', models.CharField(max_length=1000)),
                ('actions', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
