# Generated by Django 5.2 on 2025-04-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querylog',
            old_name='OriginalQuery',
            new_name='query',
        ),
    ]
